#ifndef EVENT_ID_H
#define EVENT_ID_H

/**
 * @file event_id.h
 * @brief Auto-generated event ID list for plugins.
 * @note Do not edit this file manually. Generated by generate_event_id.py.
 */

enum EventID {
    // Events for SYSTEM_EVENT_EVENT_GROUP
    PUBLIC__SYSTEM_EVENT__SYSTEM_EVENT_HEARTBEAT = 0x00100001, ///< 0x100001
    PUBLIC__SYSTEM_EVENT__SYSTEM_EVENT_SHUTDOWN  = 0x00100002, ///< 0x100002
    PUBLIC__SYSTEM_EVENT__SYSTEM_EVENT_MAX_COUNT = 0x00100003, ///< 0x100003

    // Events for LOGGER_EVENT_EVENT_GROUP
    PUBLIC__LOGGER_EVENT__LOGGER_EVENT_INFO      = 0x00300001, ///< 0x300001
    PUBLIC__LOGGER_EVENT__LOGGER_EVENT_WARN      = 0x00300002, ///< 0x300002
    PUBLIC__LOGGER_EVENT__LOGGER_EVENT_ERROR     = 0x00300003, ///< 0x300003
    PUBLIC__LOGGER_EVENT__LOGGER_EVENT_MAX_COUNT = 0x00300004, ///< 0x300004
};

#endif // EVENT_ID_H
